#
#
#  Makefile to create libArduinoCore.a for a specific board.
#
#
#
# Spec file of board to build for:

CXXSRC=RF24.cpp
SRC=

HEADERS=RF24.h RF24_config.h

LIB=../libarduinoutil.a

include ../Maketemplate
